import os
VERIFICATION_THRESHOLD=0.90
WEIGHTS={"recency":0.35,"source_count":0.30,"reliability":0.20,"duplicate_freq":0.15}
SOURCE_RELIABILITY={"reuters":1.0,"apnews":1.0,"bbc":0.95,"npr":0.95,"nbcnews":0.9,"abcnews":0.9,"cbsnews":0.9,"cnn":0.85,"gov":1.0,"google_trends_usa":0.95,"youtube_search":0.90}
RSS_FEEDS={"reuters":"http://feeds.reuters.com/reuters/topNews"}
GOOGLE_TRENDS_GEO="US"
GOOGLE_TRENDS_URL="https://trends.google.com/trending/rss?geo=US"
TREND_LIMIT=30
TREND_FILTER_A={"enabled":True,"gprop":"youtube","geo":"US","breakout_threshold":5000}
TREND_FILTER_B={"enabled":True,"half_keyword":True}
TREND_FILTER_C={"enabled":True,"bot_friendly_threshold":70}
TACKO_STYLE={"enabled":True,"segments":{"hook_0_3":{"duration":3},"news_3_15":{"duration":12},"context_15_30":{"duration":15},"cta_30_45":{"duration":15}},"titles":{"count":4}}
DAILY_KEYWORDS_PATH="data/daily_top_100.json"
TOP_KEYWORDS_COUNT=100
YOUTUBE_CATEGORY_ID="25"
YOUTUBE_PRIVACY="public"
YOUTUBE_API_KEY=os.getenv("YOUTUBE_API_KEY","")
YOUTUBE_CLIENT="youtube"
YOUTUBE_DS="yt"
YOUTUBE_GL="US"
YOUTUBE_HL="en"
VIDEO_W,VIDEO_H=1080,1920
MAX_VIDEO_DURATION=60
TARGET_MINUTES=int(os.getenv("TARGET_MINUTES","10"))
TARGET_MAX_MINUTES=int(os.getenv("TARGET_MAX_MINUTES","14"))
DB_PATH="data/news_history.db"
OUTPUT_DIR="output"
OUTPUT_LONG_DIR="output_long"
CLIPS_DIR="clips"
AUDIO_DIR="audio"
GEMINI_API_KEY=os.getenv("GEMINI_API_KEY","")
PEXELS_API_KEY=os.getenv("PEXELS_API_KEY","") or os.getenv("PEXELS_KEY","")
THRESHOLD=75
TREND_LIMIT_SHORTS=30
BOT_FRIENDLY_THRESHOLD=70
CHANNEL_NAME=os.getenv("CHANNEL_NAME","Uncovered USA")
LOG_LEVEL="INFO"
