"""
src/writing/script_generator.py - Script generation engine (FIXED Gemini models)
"""

import os
import json
import re
from src.utils.logger import setup_logger

logger = setup_logger(__name__)

# UPDATED: Working Gemini models as of 2026
GEMINI_MODELS = [
    "gemini-3.6-flash",
    "gemini-2.0-flash-exp",
    "gemini-flash-latest",
    "gemini-1.5-pro-latest",
    "gemini-pro"
]


def generate_script(story, target_duration=30):
    """Generate script for YouTube Short"""
    script = try_ai_script_generation(story, target_duration)
    
    if not script:
        script = generate_template_script(story, target_duration)
    
    return script


def try_ai_script_generation(story, target_duration):
    """Try AI script generation with multiple model fallbacks"""
    gemini_key = os.getenv("GEMINI_API_KEY", "")
    
    if not gemini_key:
        logger.warning("No GEMINI_API_KEY - using template")
        return None
    
    try:
        from google import genai
        client = genai.Client(api_key=gemini_key)
        
        topic = story.get('title', '')
        word_count = {
            20: '35-40',
            30: '45-50',
            45: '60-70',
            60: '80-90'
        }.get(target_duration, '45-50')
        
        prompt = f"""Write a YouTube Shorts script about this news topic.

TOPIC: {topic}

REQUIREMENTS:
1. First sentence = shocking hook (pattern interrupt)
2. Use "according to reports" for unverified claims
3. NO "hello guys", NO intro
4. End with open loop / "what happens next"
5. Factual, neutral, accurate
6. {word_count} words

OUTPUT JSON ONLY:
{{
    "short_script": "script here",
    "seo_youtube_title": "under 60 chars",
    "description": "SEO description",
    "hashtags": ["#breakingnews", "#worldnews"],
    "tags": ["breaking news", "world news"],
    "viral_hook": "short viral hook",
    "mood": "tense dramatic news"
}}"""
        
        # Try each model
        for model in GEMINI_MODELS:
            try:
                logger.info(f"Trying Gemini model: {model}")
                resp = client.models.generate_content(model=model, contents=prompt)
                text = getattr(resp, 'text', '')
                
                if text:
                    match = re.search(r'\{.*\}', text, re.DOTALL)
                    if match:
                        data = json.loads(match.group())
                        logger.info(f"✅ Script generated by {model}")
                        return data
            except Exception as e:
                err_msg = str(e)[:100]
                logger.warning(f"Model {model} failed: {err_msg}")
                continue
        
        logger.error("All Gemini models failed - using template")
    
    except Exception as e:
        logger.warning(f"Gemini client failed: {e}")
    
    return None


def generate_template_script(story, target_duration):
    """Template-based fallback script"""
    topic = story.get('title', 'Breaking News')
    
    scripts = {
        20: f"Breaking: {topic}. According to reports, this changes everything. Officials say the situation is developing. What happens next?",
        30: f"Breaking: {topic}. According to multiple sources, this is a major development. Officials have confirmed the basic facts. The situation continues to evolve. Here's what we know. What happens next?",
        45: f"Breaking news: {topic}. According to reports, this development could affect millions. Officials say the situation is still developing. Here's what we know so far. The key facts are still emerging. This story is developing and we will update as more information becomes available.",
        60: f"Breaking news: {topic}. According to multiple sources, this is a developing story with major implications. Officials have confirmed the basic facts but caution that the situation is still evolving. Here's what we know so far. The key questions remain unanswered. We will continue to monitor this story and provide updates as more information becomes available."
    }
    
    return {
        "short_script": scripts.get(target_duration, scripts[30]),
        "seo_youtube_title": topic[:60],
        "description": f"{topic} - breaking news update.",
        "hashtags": ["#breakingnews", "#worldnews"],
        "tags": ["breaking news", "world news", "politics"],
        "viral_hook": topic[:50],
        "mood": "tense dramatic news"
    }
