name: US Tech Shorts Bot
on:
  schedule:
    - cron: '30 12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Generate Video
        run: python bot.py
      - name: Upload Video
        uses: actions/upload-artifact@v4
        with:
          name: todays-shorts
          path: final_shorts.mp4
