name: USA Trend Shorts Auto

on:
  schedule:
    - cron: '*/20 * * * *'  # har 20 min me check - din ho ya raat
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          pip install pytrends gnews moviepy==1.0.3 Pillow requests google-api-python-client google-auth-httplib2 google-auth-oauthlib
          sudo apt-get update && sudo apt-get install -y espeak ffmpeg
          wget https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/medium/en_US-lessac-medium.onnx
          wget https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/medium/en_US-lessac-medium.onnx.json
          pip install piper-tts
      - name: Run Bot
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
        run: python bot.py
      - name: Save last trend
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@bot.com"
          git add last_trend.txt || true
          git commit -m "update trend" || true
          git push || true
